load(
    "@rules_swift//swift:swift.bzl",
    "swift_library",
)

swift_library(
    name = "UserModule",
    srcs = glob([
        # "Sources/*.swift",
        "Sources/**/*.swift",
    ]),
    module_name = "UserModule",
    visibility = ["//visibility:public"],
)
